Reorder includes
Tries to fix an issue on Windows:

TypeList.h(406,12): error C2589: '(': illegal token on right side of '::'

which is likely caused my `MAX` being a macro.